platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"
pod 'FMDB', '~> 2.5'
pod 'JSONKit-NoWarning', '~> 1.2'
#pod 'BABAudioPlayer', '~> 0.1.0'
pod "TSMessages"
pod 'SVPullToRefreshImprove', '~> 0.5'
pod 'GCNetworkReachability', '~> 1.3.2'
pod 'YTKKeyValueStore', '~> 0.1.2'
pod 'UMengAnalyticsSDK', '~> 3.6.5'
#pod 'DOUAudioStreamer', '~> 0.2.11'
pod 'PYAudioKit', '~> 0.4'
#pod 'JBAudioPlayerView', '~> 1.0.1'
pod 'JxbPlayerControl', '~> 1.0'
pod 'UIColor-MoreColors', '~> 1.1.0'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'